<?php
/**
 * @author  Luz Vargas luz.vt.89@gmail.com
 * @version  1.0
 * @package  usuarios
 * @copyright  2015
 * Archivo para ver a los usuarios que estan en la BD
 */
?>
<h2 align="center">Listado de Usuarios</h2>

<a href="<?php echo APP_URL.'usuarios/add'; ?>">Agregar Usuarios</a>
<p>
<table border="2">
	<tr>
		<th>ID</th>
		<th>Email</th>
		<th>Username</th>
		<th>Password</th>
		<th>Status</th>
		<th>Action</th>
	</tr>
	<?php foreach ($this->usuarios as $usuario): ?>
	<tr>
		<td><?php echo $usuario['id'];?></td>
		<td><?php echo $usuario['email'];?></td>
		<td><?php echo $usuario['username'];?></td>
		<td><?php echo $usuario['password'];?></td>
		<td><?php echo $usuario['status'];?></td>
		<td>
			<a href="<?php echo APP_URL."usuarios/edit/".$usuario['id']; ?>">Editar</a> |
			<a href="<?php echo APP_URL."usuarios/delete/".$usuario['id']; ?>">Eliminar</a>
		</td>
	</tr>
	<?php endforeach ?>
</table>