<?php
/**
 * @author  Luz Vargas luz.vt.89@gmail.com
 * @version  1.0
 * @package  tareas
 * @copyright  2015
 * Archivo pra editar tareas
 * @method  POST
 */
?>
<h2 align="center">Editar tareas</h2>

<form action="<?php APP_URL.'tareas/edit';?>" method="POST" align="center">

	<input type="hidden" name="id" value="<?php echo $this->tarea['id']; ?>">
	<p>Nombre: <input type="text" name="nombre" value="<?php echo $this->tarea['nombre']; ?>"></p>
	<p>Fecha: <input type="text" name="fecha" value="<?php echo $this->tarea['fecha']; ?>"></p>
	<p>Prioridad: <input type="text" name="prioridad" value="<?php echo $this->tarea['prioridad']; ?>"></p>
	<p>Status: <input type="text" name="status" value="<?php echo $this->tarea['status']; ?>"></p>
	<p><input type="submit"></p>
</form>
